name: "CD: executor (staging)"

on:
  push:
    branches:
      - 'deploy-executor-staging'

env:
  BUILD_DIRECTORY: "executor"
  TAG_VERSION: "v0-latest"
  DOCKER_REPO_NAME: "backenddevelopersltd/compute-horde-executor-staging"
  DIST_VERSION_PREFIX: "executor-staging"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Docker build and push
        run: |
          IMAGE_NAME="${DOCKER_REPO_NAME}:${TAG_VERSION}"
          SHA_IMAGE_NAME="${DOCKER_REPO_NAME}:git-${GITHUB_SHA}"

          cd "${BUILD_DIRECTORY}" && docker build --build-context compute-horde=../compute_horde -t "${IMAGE_NAME}" -f app/envs/prod/Dockerfile .

          docker image tag "${IMAGE_NAME}" "${SHA_IMAGE_NAME}"

          echo "${{ secrets.DOCKERHUB_KEY }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

          docker push "${IMAGE_NAME}"
          docker push "${SHA_IMAGE_NAME}"
  
  tagging:
    needs: deploy
    uses: ./.github/workflows/common_tagging.yml
    with:
      DIST_VERSION_PREFIX: "executor-staging"
