name: "CD: miner (pre-prod)"

on:
  push:
    branches:
      - 'deploy-miner-preprod'

env:
  TAG_VERSION: "v0-latest"
  STAGING_DOCKER_REPO_NAME: "backenddevelopersltd/compute-horde-miner-staging"
  DOCKER_REPO_NAME: "backenddevelopersltd/compute-horde-miner-preprod"
  DIST_VERSION_PREFIX: "miner-preprod"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Docker build and push
        run: |
          IMAGE_NAME="${DOCKER_REPO_NAME}:${TAG_VERSION}"
          SHA_IMAGE_NAME="${STAGING_DOCKER_REPO_NAME}:git-${GITHUB_SHA}"

          docker pull "${SHA_IMAGE_NAME}"
          docker image tag "${SHA_IMAGE_NAME}" "${IMAGE_NAME}"

          echo "${{ secrets.DOCKERHUB_KEY }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

          docker push "${IMAGE_NAME}"
  
  tagging:
    needs: deploy
    uses: ./.github/workflows/common_tagging.yml
    with:
      DIST_VERSION_PREFIX: "miner-preprod"
