name: "CD: miner runner (staging)"

on:
  push:
    branches:
      - 'deploy-miner-runner-staging'

env:
  BUILD_DIRECTORY: "miner/envs/runner"
  TAG_VERSION: "v0-latest"
  DOCKER_REPO_NAME: "backenddevelopersltd/compute-horde-miner-runner-staging"
  DOCKER_NGINX_REPO_NAME: "backenddevelopersltd/compute-horde-miner-nginx-staging"
  MINER_IMAGE_REPO: "compute-horde-miner-staging"
  MINER_NGINX_IMAGE_REPO: "compute-horde-miner-nginx-staging"
  DIST_VERSION_PREFIX: "miner-runner-staging"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Docker build and push
        run: |
          IMAGE_NAME="${DOCKER_REPO_NAME}:${TAG_VERSION}"
          SHA_IMAGE_NAME="${DOCKER_REPO_NAME}:git-${GITHUB_SHA}"

          cd "${BUILD_DIRECTORY}" && \
            docker build \
            -t "${IMAGE_NAME}" \
            --build-arg MINER_RUNNER_VERSION="${GITHUB_SHA}" \
            --build-arg MINER_IMAGE_REPO="${MINER_IMAGE_REPO}" \
            --build-arg MINER_NGINX_IMAGE_REPO="${MINER_NGINX_IMAGE_REPO}" \
            .

          docker image tag "${IMAGE_NAME}" "${SHA_IMAGE_NAME}"

          echo "${{ secrets.DOCKERHUB_KEY }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

          docker push "${IMAGE_NAME}"
          docker push "${SHA_IMAGE_NAME}"
      - name: Docker build and push (nginx)
        run: |
          IMAGE_NAME="${DOCKER_NGINX_REPO_NAME}:${TAG_VERSION}"
          SHA_IMAGE_NAME="${DOCKER_NGINX_REPO_NAME}:git-${GITHUB_SHA}"

          cd "${BUILD_DIRECTORY}/nginx" && \
            docker build \
            -t "${IMAGE_NAME}" \
            .

          docker image tag "${IMAGE_NAME}" "${SHA_IMAGE_NAME}"

          echo "${{ secrets.DOCKERHUB_KEY }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

          docker push "${IMAGE_NAME}"
          docker push "${SHA_IMAGE_NAME}"
  
  tagging:
    needs: deploy
    uses: ./.github/workflows/common_tagging.yml
    with:
      DIST_VERSION_PREFIX: "miner-runner-staging"
    secrets:
      ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
