name: "CD: validator runner (staging)"

on:
  push:
    branches:
      - 'deploy-validator-runner-staging'

env:
  BUILD_DIRECTORY: "validator/envs/runner"
  TAG_VERSION: "v0-latest"
  DOCKER_REPO_NAME: "backenddevelopersltd/compute-horde-validator-runner-staging"
  VALIDATOR_IMAGE_REPO: "compute-horde-validator-staging"
  DIST_VERSION_PREFIX: "validator-runner-staging"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Docker build and push
        run: |
          IMAGE_NAME="${DOCKER_REPO_NAME}:${TAG_VERSION}"
          SHA_IMAGE_NAME="${DOCKER_REPO_NAME}:git-${GITHUB_SHA}"

          cd "${BUILD_DIRECTORY}" && \
            docker build \
            -t "${IMAGE_NAME}" \
            --build-arg VALIDATOR_RUNNER_VERSION="${GITHUB_SHA}" \
            --build-arg VALIDATOR_IMAGE_REPO="${VALIDATOR_IMAGE_REPO}" \
            .

          docker image tag "${IMAGE_NAME}" "${SHA_IMAGE_NAME}"

          echo "${{ secrets.DOCKERHUB_KEY }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

          docker push "${IMAGE_NAME}"
          docker push "${SHA_IMAGE_NAME}"
  
  tagging:
    needs: deploy
    uses: ./.github/workflows/common_tagging.yml
    with:
      DIST_VERSION_PREFIX: "validator-runner-staging"
